[tool.poetry]
name = "http-service-requests"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.1"
djangorestframework = "^3.16.0"
djangorestframework-simplejwt = "^5.5.0"
pytest = "^8.3.5"
pytest-django = "^4.11.1"
python-dotenv = "^1.1.0"
psycopg2-binary = "^2.9.10"
django-cors-headers = "^4.7.0"
django-celery-beat = "^2.8.1"
drf-yasg = "^1.21.10"
flake8 = "^7.2.0"
black = "^25.1.0"
django-filter = "^25.1"
httpx = "^0.28.1"
channels = "^4.2.2"
asgiref = "^3.8.1"
aiohttp = "^3.11.18"
asyncio = "^3.4.3"
celery = "^5.5.2"
requests = "^2.32.3"
uvicorn = "^0.34.2"


[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
