# Generated by Django 5.2.1 on 2025-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URLrequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField()),
                ("short_id", models.CharField(max_length=6, unique=True)),
            ],
            options={
                "verbose_name": "url",
                "verbose_name_plural": "urls",
            },
        ),
    ]
