# Generated by Django 5.2.1 on 2025-05-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shorturl", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="urlrequest",
            options={"verbose_name": "urll", "verbose_name_plural": "urls"},
        ),
    ]
