# Generated by Django 5.2.1 on 2025-05-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shorturl", "0002_alter_urlrequest_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="urlrequest",
            options={"verbose_name": "url", "verbose_name_plural": "urls"},
        ),
    ]
