# Generated by Django 5.2.1 on 2025-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shorturl", "0003_alter_urlrequest_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlrequest",
            name="original_url",
            field=models.URLField(unique=True),
        ),
    ]
